# Generated by Django 6.0.1 on 2026-02-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='nzc.learningarea')),
            ],
        ),
        migrations.CreateModel(
            name='NZCExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=20)),
                ('year_level', models.PositiveIntegerField(blank=True, null=True)),
                ('expectation_text', models.TextField()),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('progression_code', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='nzc.strand')),
            ],
        ),
    ]
