# Generated by Django 6.0.1 on 2026-01-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_categories_course_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
