# Generated by Django 6.0.1 on 2026-01-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['level', 'title']},
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='bg-gray-100', max_length=30),
        ),
    ]
