# Generated by Django 6.0.1 on 2026-01-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options_alter_category_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='SubCategory',
        ),
    ]
