# Generated by Django 6.0.1 on 2026-01-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='subcategory',
        ),
    ]
