# Generated by Django 6.0.1 on 2026-01-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_category_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blurb',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='color',
            field=models.CharField(default='gray', max_length=30),
        ),
    ]
