# Generated by Django 6.0.1 on 2026-01-31 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_blurb_alter_subcategory_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='blurb',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
