# Generated by Django 6.0.1 on 2026-01-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_course_subcategory_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='neutral', max_length=10),
        ),
    ]
