# Generated by Django 6.0.1 on 2026-01-31 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField()),
                ('credits', models.PositiveIntegerField()),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('is_achievement', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('estimated_weeks', models.PositiveIntegerField(default=4)),
                ('resources', models.JSONField(blank=True, default=dict)),
                ('assessment_criteria', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courses.course')),
                ('standards', models.ManyToManyField(blank=True, related_name='blocks', to='courses.standard')),
            ],
            options={
                'ordering': ['course', 'title'],
            },
        ),
    ]
