# Generated by Django 6.0.1 on 2026-01-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_standard_block'),
        ('standards', '0002_alter_standard_assessment_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Standard',
        ),
        migrations.AlterField(
            model_name='block',
            name='standards',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='standards.standard'),
        ),
    ]
