# Generated by Django 6.0.1 on 2026-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_number', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField()),
                ('credits', models.PositiveSmallIntegerField()),
                ('assessment_type', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=20)),
                ('version', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('current', 'Current'), ('expiring', 'Expiring'), ('expired', 'Expired')], default='current', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['standard_number'],
            },
        ),
    ]
