# Generated by Django 6.0.1 on 2026-01-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='assessment_type',
            field=models.CharField(default='Achievement Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='standard',
            name='credits',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='standard',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='standard',
            name='mode',
            field=models.CharField(default='Internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='standard',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
