# Generated by Django 6.0.1 on 2026-01-31 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('standards', '0002_alter_standard_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='data.category'),
        ),
    ]
