# Generated by Django 6.0.1 on 2026-02-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_standard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='curriculum',
            field=models.CharField(choices=[('NZC', 'New Zealand Curriculum'), ('NCEA', 'NCEA'), ('NZQA', 'NZQA')], default='NCEA', max_length=10),
        ),
    ]
