# Generated by Django 6.0.1 on 2026-02-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0004_standard_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='curriculum',
            field=models.CharField(choices=[('NZC', 'NZC'), ('NCEA', 'NCEA'), ('NZQA', 'NZQA')], default='NCEA', max_length=10),
        ),
    ]
