# Generated by Django 6.0.1 on 2026-02-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0005_alter_standard_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='credits',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='level',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='standard',
            name='standard_number',
            field=models.CharField(default='AS92L', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('pending', 'Pending'), ('review', 'Review')], default='pending', max_length=10),
        ),
    ]
